language: generic

sudo: true

env:
  matrix:
    - VERSION=4.6 TAG=4.6
    - VERSION=4.7 TAG=4.7
    - VERSION=4.7

services:
  - docker

before_script:
  - make create VERSION=${VERSION} TAG=${TAG}

script:
  - docker inspect "leodido/antlr"$([ -n "$TAG" ] && echo ":${TAG}")

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then  
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
      make deploy TAG=${TAG};
    fi